// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Experience struct {
	ID                 string          `json:"id"`
	Company            string          `json:"company"`
	Role               string          `json:"role"`
	StartDate          time.Time       `json:"start_date"`
	EndDate            sql.NullTime    `json:"end_date"`
	Description        json.RawMessage `json:"description"`
	TechStack          json.RawMessage `json:"tech_stack"`
	SecurityHighlights json.RawMessage `json:"security_highlights"`
	Metadata           json.RawMessage `json:"metadata"`
	IsPublished        bool            `json:"is_published"`
	SortOrder          int32           `json:"sort_order"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type Profile struct {
	Key     string          `json:"key"`
	Content json.RawMessage `json:"content"`
}
