// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getFullProfile = `-- name: GetFullProfile :many
SELECT key, content FROM profile ORDER BY key
`

func (q *Queries) GetFullProfile(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getFullProfile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(&i.Key, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileSection = `-- name: GetProfileSection :one
SELECT content FROM profile WHERE key = $1
`

func (q *Queries) GetProfileSection(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getProfileSection, key)
	var content json.RawMessage
	err := row.Scan(&content)
	return content, err
}

const getPublishedExperiences = `-- name: GetPublishedExperiences :many
SELECT id, company, role, start_date, end_date, description, tech_stack, security_highlights, metadata, created_at
FROM experiences
WHERE is_published = true
ORDER BY sort_order ASC, start_date DESC
`

type GetPublishedExperiencesRow struct {
	ID                 string          `json:"id"`
	Company            string          `json:"company"`
	Role               string          `json:"role"`
	StartDate          time.Time       `json:"start_date"`
	EndDate            sql.NullTime    `json:"end_date"`
	Description        json.RawMessage `json:"description"`
	TechStack          json.RawMessage `json:"tech_stack"`
	SecurityHighlights json.RawMessage `json:"security_highlights"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
}

func (q *Queries) GetPublishedExperiences(ctx context.Context) ([]GetPublishedExperiencesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPublishedExperiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublishedExperiencesRow{}
	for rows.Next() {
		var i GetPublishedExperiencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.TechStack,
			&i.SecurityHighlights,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
